// app/(tabs)/workouts.tsx
import { router } from "expo-router";
import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

import { Card } from "../../src/components/Card";
import { PrimaryButton } from "../../src/components/PrimaryButton";
import { Screen } from "../../src/components/Screen";
import { theme } from "../../src/constants/theme";

import { startWorkout, getWorkouts } from "../../src/lib/workouts";
import type { WorkoutSession } from "../../src/lib/workouts";

import { useSession } from "../../src/session/SessionContext";

function formatDate(v?: string | null) {
  if (!v) return "—";
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleString();
}

export default function WorkoutsScreen() {
  const { user, loading: sessionLoading } = useSession();
  const userId = user?.id;

  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [sessions, setSessions] = useState<WorkoutSession[]>([]);

  const hasSessions = sessions.length > 0;

  const load = async () => {
    if (sessionLoading) return;

    if (!userId) {
      setErr("No user session found. Please log in again.");
      setLoading(false);
      return;
    }

    setLoading(true);
    setErr(null);
    try {
      const data = await getWorkouts(userId);
      setSessions(data || []);
    } catch (e: any) {
      const msg = e?.message ?? "Failed to load workouts";
      setErr(String(msg));
    } finally {
      setLoading(false);
    }
  };

  // Quick Add now uses the REAL schema:
  // - duration_min is generated by DB when ended_at is set
  // - so "quick add" should start a workout (ended_at null) OR you add a separate "log workout" flow later
  const onQuickAdd = async () => {
    if (sessionLoading) return;

    if (!userId) {
      setErr("No user session found. Please log in again.");
      return;
    }

    setLoading(true);
    setErr(null);
    try {
      await startWorkout({
        userId,
        title: "Quick Session",
        activityType: "strength",
      });
      await load();
    } catch (e: any) {
      const msg = e?.message ?? "Failed to create workout";
      setErr(String(msg));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!sessionLoading && userId) load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionLoading, userId]);

  const title = useMemo(() => {
    if (loading) return "Workouts";
    if (err) return "Workouts";
    return hasSessions ? `Workouts (${sessions.length})` : "Workouts";
  }, [loading, err, hasSessions, sessions.length]);

  return (
    <Screen>
      <View style={styles.header}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.sub}>Your logged sessions</Text>
      </View>

      <View style={{ marginBottom: theme.spacing.md }}>
        <PrimaryButton label="Quick Add Workout" onPress={onQuickAdd} />
      </View>

      {loading ? (
        <Card>
          <View style={styles.center}>
            <ActivityIndicator />
            <Text style={styles.meta}>
              {sessionLoading ? "Loading session…" : "Loading workouts…"}
            </Text>
          </View>
        </Card>
      ) : err ? (
        <Card>
          <Text style={styles.errorText}>{err}</Text>
          <View style={{ marginTop: theme.spacing.md }}>
            <PrimaryButton label="Retry" onPress={load} />
          </View>
        </Card>
      ) : !hasSessions ? (
        <Card>
          <Text style={styles.meta}>No workouts yet.</Text>
          <Text style={[styles.meta, { marginTop: 6 }]}>
            When you log a session, it will appear here.
          </Text>
          <View style={{ marginTop: theme.spacing.md }}>
            <PrimaryButton label="Refresh" onPress={load} />
          </View>
        </Card>
      ) : (
        <View style={{ gap: 12 }}>
          {sessions.map((s) => {
            const started = s.started_at ?? s.created_at ?? null;

            return (
              <Pressable
                key={s.id}
                onPress={() => router.push(`/workout/${encodeURIComponent(s.id)}`)}
                style={({ pressed }) => [pressed && { opacity: 0.9 }]}
              >
                <Card>
                  <Text style={styles.rowTitle}>{s.title ?? "Workout Session"}</Text>

                  <Text style={styles.meta}>
                    {s.activity_type ?? "WORKOUT"}
                    {started ? ` • ${formatDate(started)}` : ""}
                    {s.ended_at ? ` • ended ${formatDate(s.ended_at)}` : " • active"}
                  </Text>

                  {typeof s.duration_min === "number" ? (
                    <Text style={styles.meta}>{s.duration_min} min</Text>
                  ) : null}
                </Card>
              </Pressable>
            );
          })}

          <View style={{ height: 4 }} />
          <PrimaryButton label="Refresh" onPress={load} />
        </View>
      )}
    </Screen>
  );
}

const styles = StyleSheet.create({
  header: { marginBottom: theme.spacing.lg },
  title: { color: theme.colors.text, fontSize: 24, fontWeight: "900" },
  sub: { color: theme.colors.textMuted, marginTop: 6, fontWeight: "700" },

  center: { alignItems: "center", paddingVertical: 10 },
  meta: { color: theme.colors.textMuted, marginTop: 8, fontWeight: "700" },
  errorText: { color: "#ff6b6b", fontWeight: "800" },

  rowTitle: { color: theme.colors.text, fontSize: 16, fontWeight: "900" },
});